import type { Metadata } from "next";
import { CtaBand, PageHero, SiteFooter, SiteHeader } from "../components/SiteChrome";

export const metadata: Metadata = { title: "Over ons | ATW Montage", description: "Maak kennis met ATW Montage: VCA-gecertificeerd vakmanschap, korte lijnen en landelijke inzet." };

export default function OverOnsPage() {
  return <main><SiteHeader /><PageHero eyebrow="Over ATW Montage" title="Vakmanschap dat" accent="vertrouwen geeft." copy="We bouwen niet alleen aan woningen. We bouwen aan een samenwerking waarin afspraken duidelijk zijn en kwaliteit zichtbaar wordt." image="craft" />
    <section className="about-story" data-reveal><div className="about-image"><div className="craft-stamp"><span>ATW</span><small>Vakwerk<br />sinds dag één</small></div></div><div className="about-copy"><p className="kicker">Onze manier van werken</p><h2>Persoonlijk betrokken.<br />Professioneel uitgevoerd.</h2><p>ATW Montage neemt complete verbouwingen aan voor particuliere opdrachtgevers. Vanuit één aanspreekpunt organiseren we de werkzaamheden, bewaken we de voortgang en zorgen we dat ieder onderdeel op het volgende aansluit.</p><p>Onze kracht zit in de combinatie van ambachtelijk timmerwerk en overzicht over het gehele project. Geen onnodig ingewikkelde communicatie, maar duidelijke keuzes, praktische oplossingen en werk waarop u kunt vertrouwen.</p><div className="about-facts"><div><strong>5+</strong><span>jaar ervaring</span></div><div><strong>VCA</strong><span>gecertificeerd</span></div><div><strong>NL</strong><span>landelijk actief</span></div></div></div></section>
    <section className="values-section"><div><p className="kicker light">Waar wij voor staan</p><h2>De basis van ieder project.</h2></div><div className="value-grid"><article><span>01</span><h3>Vakmanschap</h3><p>Materialen, maatvoering en afwerking krijgen de aandacht die ze verdienen.</p></article><article><span>02</span><h3>Afspraak is afspraak</h3><p>We communiceren helder over planning, keuzes en voortgang.</p></article><article><span>03</span><h3>Eigenaarschap</h3><p>We denken mee, signaleren op tijd en voelen ons verantwoordelijk voor het eindresultaat.</p></article><article><span>04</span><h3>Veilig werken</h3><p>VCA-gecertificeerde vakmensen en een bewuste aanpak op iedere werkplek.</p></article></div></section>
    <section className="reference-statement"><p>Referenties</p><blockquote>“Goed werk mag u controleren.”</blockquote><span>Daarom delen we referenties van afgeronde projecten graag tijdens een kennismaking.</span></section>
    <CtaBand title="Laten we bouwen aan een woning die klopt." /><SiteFooter /></main>;
}
